Repository kaldi-asr/kaldi, pull requests merged in 2020-06, with the labels that each got.

#4018 Update wer_output_filter
  egs/thchs30/s5/local/wer_output_filter
Labels: stale

#4001 modify chain2 script (add ivector, diagnosis log, compute_wer.sh), and add wer results for mini_librispeech and wsj
  .gitpod.Dockerfile
  .gitpod.yml
  README.md
  egs/mini_librispeech/s5/cmd.sh
  egs/mini_librispeech/s5/local/chain2/compare_wer.sh
  egs/mini_librispeech/s5/local/chain2/data_prep_common.sh
  egs/mini_librispeech/s5/local/chain2/tuning/run_tdnn_1a.sh
  egs/wsj/s5/local/chain2/compare_wer.sh
  egs/wsj/s5/local/chain2/run_tdnn.sh
  egs/wsj/s5/local/chain2/tuning/run_tdnn_1i.sh
  egs/wsj/s5/run.sh
  egs/wsj/s5/steps/nnet3/chain2/train.sh
Labels: chain2

#4132 Extend stale timeout and exempt certain labels
  .github/stale.yml
Labels: in progress
