Repository kaldi-asr/kaldi, pull requests merged in 2020-07, with the labels that each got.

#4133 [build] Undo OpenFST Makefile patch hack from #4177
  tools/Makefile
Labels: in progress

#4172 add use-gpu option
  scripts/rnnlm/compute_perplexity.sh
Labels: waiting-for-feedback

#3807 add support to read/write `*.npy` format.
  src/base/kaldi-utils.h
  src/matrix/Makefile
  src/matrix/matrix-lib.h
  src/matrix/numpy-array-test.cc
  src/matrix/numpy-array.cc
  src/matrix/numpy-array.h
  src/matrix/test_data/README
  src/matrix/test_data/double_matrix.npy
  src/matrix/test_data/double_matrix_big_endian.npy
  src/matrix/test_data/double_vector.npy
  src/matrix/test_data/double_vector_big_endian.npy
  src/matrix/test_data/float_matrix.npy
  src/matrix/test_data/float_matrix_big_endian.npy
  src/matrix/test_data/float_vector.npy
  src/matrix/test_data/float_vector_big_endian.npy
  src/matrix/test_data/generate_numpy_array_test_data.py
  src/util/kaldi-table-test.cc
  src/util/table-types.h
Labels: stale-exclude
